### ISSUE TITLE
Can you please elaborate how a PHP server will send callback to the application?

### ISSUE THREAD

**Issue by swapnil1104** [charanolati/Android-PayPal-Integration-SDK#1]
I'm trying to integrate the same along with a RoR server, please guide me through the same.

**Comment by charanolati** [comment]
The PHP Server Automatically calls your Applications Activity Intent which is declared in Manifest as `<data android:scheme="com.gurucharan.paypalcustomtabdemo"/>`  for Success/Failure Upon the completion of Payment

To Call your Intent , you have to call a  **Sever Side 302 redirect**  by using 

`$url ="Location:com.gurucharan.paypalcustomtabdemo:success/".$body_id."/".$body_payer_payer_info_payer_id;
header('$url', true, 302);
exit;` at your Server Side/Php Files

The Server will call your App by using `com.gurucharan.paypalcustomtabdemo` , So Change the intent as your application needed

The body id , Payer info , Payer ID will be getting from PAY-PAL server to Your Server after Completion of Payment

The Most of the payment part will be Done at web where you host your Rest server/Files,
In Simple words you are just using WebView to Complete your Payment
