### ISSUE TITLE
error occur when response come from paypal in your demo. please solve that

### ISSUE THREAD

**Issue by rajam1215** [charanolati/Android-PayPal-Integration-SDK#2]
{
	"name": "VALIDATION_ERROR",
	"details": [{
		"field": "redirect_urls.cancel_url",
		"issue": "{Url}"
	}, {
		"field": "redirect_urls.return_url",
		"issue": "{Url}"
	}],
	"message": "Invalid request - see details",
	"information_link": "https:\/\/developer.paypal.com\/docs\/api\/payments\/#errors",
	"debug_id": "d1024ff9bdae0"
}

**Comment by rajam1215** [comment]
@charanolati 
Hello charan , i have this issue in payment gateway with your library, please give me some solution . this is very good library. 
thanks

**Comment by charanolati** [comment]
@rajam1215 
This particular version with Paypal SDK is Deprecated 
Use this [LINK](https://developer.paypal.com/docs/api/payments/v2/) to integrate the Paypal SDK
